name: ae2
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2023.11.17=hbcca054_0
  - cpuonly=1.0=0
  - cudatoolkit=11.3.1=h9edb442_10
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.10.4=h0708190_1
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9b=h024ee3a_2
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.17=h166bdaf_0
  - libpng=1.6.37=h21135ba_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.1.0=h2733197_1
  - libuv=1.43.0=h7f98852_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py39h7e14d7c_0
  - mkl_fft=1.3.1=py39h0c7bc48_1
  - mkl_random=1.2.2=py39hde0f152_0
  - ncurses=6.3=h5eee18b_3
  - nettle=3.6=he412f7d_0
  - ninja=1.11.0=h924138e_0
  - numpy-base=1.24.3=py39h31eccc5_0
  - olefile=0.46=pyh9f0ad1d_1
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.4.0=hf7af979_0
  - openssl=1.1.1w=h7f8727e_0
  - pip=22.3.1=py39h06a4308_0
  - python=3.9.15=h7a1cb2a_2
  - python_abi=3.9=2_cp39
  - readline=8.2=h5eee18b_0
  - setuptools=65.5.0=py39h06a4308_0
  - sqlite=3.40.0=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - typing_extensions=4.8.0=pyha770c72_0
  - tzdata=2022g=h04d1e81_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.8=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.4.9=ha95c52a_0
  - pip:
    - absl-py==1.3.0
    - aiohttp==3.8.3
    - aiosignal==1.3.1
    - antlr4-python3-runtime==4.8
    - anyio==3.6.2
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.2.3
    - asttokens==2.2.1
    - astunparse==1.6.3
    - async-timeout==4.0.2
    - attrs==22.1.0
    - av==10.0.0
    - backcall==0.2.0
    - beautifulsoup4==4.9.3
    - bleach==6.0.0
    - brotli==1.0.9
    - cachetools==5.2.0
    - certifi==2020.12.5
    - cffi==1.15.1
    - charset-normalizer==2.1.1
    - click==8.1.3
    - comm==0.1.2
    - cryptography==39.0.0
    - cycler==0.10.0
    - debugpy==1.6.6
    - decorator==4.4.2
    - defusedxml==0.7.1
    - docopt==0.6.2
    - dtw==1.4.0
    - easydict==1.10
    - editdistance==0.6.2
    - egl-probe==1.0.2
    - einops==0.6.0
    - executing==1.2.0
    - fastjsonschema==2.16.2
    - ffmpeg-python==0.2.0
    - filelock==3.12.4
    - flake8==3.9.1
    - flatbuffers==22.11.23
    - fqdn==1.5.1
    - frozenlist==1.3.3
    - fsspec==2023.9.2
    - future==0.18.3
    - fuzzy-c-means==1.6.4
    - fvcore==0.1.5.post20221221
    - gast==0.4.0
    - glfw==2.5.6
    - google-api-core==2.11.0
    - google-api-python-client==2.76.0
    - google-auth==2.14.1
    - google-auth-httplib2==0.1.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - googleapis-common-protos==1.58.0
    - grpcio==1.50.0
    - h5py==3.7.0
    - httplib2==0.21.0
    - huggingface-hub==0.17.3
    - humanize==4.8.0
    - hydra-core==1.1.1
    - idna==3.4
    - ignite==1.1.0
    - imageio==2.26.0
    - imageio-ffmpeg==0.4.8
    - importlib-metadata==5.1.0
    - iopath==0.1.10
    - ipykernel==6.20.2
    - ipython==8.9.0
    - ipython-genutils==0.2.0
    - ipywidgets==8.0.4
    - isoduration==20.11.0
    - jedi==0.18.2
    - jinja2==3.0.1
    - joblib==1.2.0
    - jsonpointer==2.3
    - jsonschema==4.17.3
    - jupyter==1.0.0
    - jupyter-client==8.0.2
    - jupyter-console==6.4.4
    - jupyter-core==5.2.0
    - jupyter-events==0.6.3
    - jupyter-server==2.1.0
    - jupyter-server-terminals==0.4.4
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==3.0.5
    - keras==2.11.0
    - keras-applications==1.0.8
    - kiwisolver==1.3.1
    - libclang==14.0.6
    - lightning-utilities==0.4.2
    - lit==16.0.5.post0
    - llvmlite==0.39.1
    - lxml==4.6.3
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib==3.4.2
    - matplotlib-inline==0.1.6
    - mccabe==0.6.1
    - mediapipe==0.9.1.0
    - mistune==2.0.4
    - moviepy==1.0.3
    - mpmath==1.3.0
    - mujoco==2.3.2
    - multidict==6.0.3
    - mutagen==1.46.0
    - mxnet-cu110==1.9.1
    - nbclassic==0.5.1
    - nbclient==0.7.2
    - nbconvert==7.2.9
    - nbformat==5.7.3
    - nest-asyncio==1.5.6
    - networkx==3.1
    - notebook==6.5.2
    - notebook-shim==0.2.2
    - numba==0.56.4
    - numpy==1.23.5
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - oauth2client==4.1.3
    - oauthlib==3.2.2
    - omegaconf==2.1.1
    - opencv-contrib-python==4.5.1.48
    - opencv-python==4.5.2.52
    - opt-einsum==3.3.0
    - packaging==21.3
    - pandas==1.2.4
    - pandocfilters==1.5.0
    - parameterized==0.9.0
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==8.2.0
    - platformdirs==2.6.2
    - portalocker==2.7.0
    - proglog==0.1.10
    - projectaria-tools==0.0.3
    - prometheus-client==0.16.0
    - prompt-toolkit==3.0.36
    - protobuf==3.19.6
    - psutil==5.9.4
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycodestyle==2.7.0
    - pycparser==2.21
    - pycryptodomex==3.18.0
    - pydantic==1.10.2
    - pydrive2==1.15.0
    - pyflakes==2.3.1
    - pygments==2.14.0
    - pymaxflow==1.2.13
    - pyopengl==3.1.6
    - pyopenssl==23.0.0
    - pyparsing==2.4.7
    - pyrsistent==0.19.3
    - python-dateutil==2.8.2
    - python-graphviz==0.8.4
    - python-json-logger==2.0.4
    - python-version==0.0.2
    - pytorch-ignite==0.4.11
    - pytorch-lightning==1.8.4.post0
    - pytorchvideo==0.1.5
    - pytz==2021.1
    - pyyaml==5.4.1
    - pyzmq==25.0.0
    - qtconsole==5.4.0
    - qtpy==2.3.0
    - regex==2023.10.3
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - robomimic==0.2.0
    - robosuite==1.4.0
    - rsa==4.9
    - safetensors==0.4.0
    - scikit-learn==1.1.3
    - scipy==1.9.3
    - seaborn==0.12.2
    - send2trash==1.8.0
    - sh==1.14.2
    - simplejson==3.19.1
    - six==1.15.0
    - sklearn==0.0.post1
    - sniffio==1.3.0
    - soundfile==0.11.0
    - soupsieve==2.2.1
    - stack-data==0.6.2
    - tabulate==0.8.10
    - tensorboard==2.11.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.5.1
    - tensorflow==2.11.0
    - tensorflow-estimator==2.11.0
    - tensorflow-hub==0.14.0
    - tensorflow-io-gcs-filesystem==0.28.0
    - termcolor==2.1.1
    - terminado==0.17.1
    - threadpoolctl==3.1.0
    - timm==0.4.12
    - tinycss2==1.2.1
    - tokenizers==0.14.1
    - torch==1.10.1+cu111
    - torchaudio==0.10.1+cu111
    - torchmetrics==0.11.0
    - torchvision==0.11.2+cu111
    - tornado==6.2
    - tqdm==4.61.0
    - traitlets==5.9.0
    - transformers==4.34.0
    - typer==0.4.2
    - typing-extensions==4.4.0
    - uri-template==1.2.0
    - uritemplate==4.1.1
    - urllib3==1.26.13
    - wcwidth==0.2.6
    - webcolors==1.12
    - webencodings==0.5.1
    - websocket-client==1.5.0
    - websockets==11.0.3
    - werkzeug==2.2.2
    - widgetsnbextension==4.0.5
    - wrapt==1.14.1
    - yacs==0.1.8
    - yarl==1.8.2
    - youtube-dl==2021.12.17
    - yt-dlp==2023.7.6
    - zipp==3.11.0
